apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello-qa
spec:
  template:
    spec:
      containers:
      - name: hello
        image: us-docker.pkg.dev/cloudrun/container/hello
        ports:
        - containerPort: 8080
